import "./globals.css";
import "@fontsource/roboto/300.css";
import HeaderLayout from "@/layouts/Header";
import { UserProvider } from "@/lib/app/contexts/user";
import { LoadingProvider } from "@/lib/app/contexts/loading";
import AppLayout from "@/layouts/AppLayouts";
import ThemeUI from "@/components/ThemeUI";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Netflix+",
  description: "Generated by nextjs 14",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ThemeUI>
          <UserProvider>
            <LoadingProvider>
              <AppLayout>
                <HeaderLayout />
                {children}
              </AppLayout>
            </LoadingProvider>
          </UserProvider>
        </ThemeUI>
      </body>
    </html>
  );
}
