import FirstComponent from "@/components/first";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "MUI",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <>
      <FirstComponent />
    </>
  );
}
