import FirstComponent from "@/components/first";
import { Metadata } from "next";
import Head from "next/head";

export const metadata: Metadata = {
  title: "MUI",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <>
      <Head>
        <link rel="icon" href="/logoicon.ico" />
      </Head>
      <FirstComponent />
    </>
  );
}
